"""empty message

<<<<<<<< HEAD:migrations/versions/545dce83ec28_.py
Revision ID: 545dce83ec28
Revises: 
Create Date: 2022-05-18 03:59:57.813191
========
Revision ID: 1b257ffbde14
Revises: 
Create Date: 2022-04-29 02:59:44.423673
>>>>>>>> 8651dd5a29957cc1ea950b3a7efa04ff9a4f9f97:migrations/versions/1b257ffbde14_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/545dce83ec28_.py
revision = '545dce83ec28'
========
revision = '1b257ffbde14'
>>>>>>>> 8651dd5a29957cc1ea950b3a7efa04ff9a4f9f97:migrations/versions/1b257ffbde14_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_content',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('press', sa.String(length=20), nullable=False),
    sa.Column('press_url', sa.String(length=50), nullable=False),
    sa.Column('logo_url', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('content', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('types', sa.String(length=10), nullable=False),
    sa.Column('interest_cnt', sa.Integer(), nullable=False),
    sa.Column('com_cnt', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=200), nullable=False),
    sa.Column('summaries1', sa.String(), nullable=False),
    sa.Column('summaries2', sa.String(), nullable=True),
    sa.Column('summaries3', sa.String(), nullable=True),
    sa.Column('hash1', sa.String(length=10), nullable=False),
    sa.Column('hash2', sa.String(length=10), nullable=False),
    sa.Column('hash3', sa.String(length=10), nullable=False),
    sa.Column('hash4', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('news_id', name=op.f('pk_news_content'))
    )
    op.create_table('news_hashtag',
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('hash_id', name=op.f('pk_news_hashtag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_hashtag')
    op.drop_table('news_content')
    # ### end Alembic commands ###
